-- Baseline of current production/dev Supabase schema as of 2026-06-25.
-- Earlier manual SQL changes may not have individual migrations.
-- Future schema changes should be added as separate migrations.

create table if not exists ...
alter table ... add column if not exists ...
create policy ...